- name: Play - Install and configure Nginx as a LoadBalancer
  hosts: localhost
  become: true
  tasks:
    - name: Update cache
      apt:
        update_cache: yes
        #cache_valid_time: 3600  # Optional: Cache valid time in seconds

    - name: Install Nginx
      apt:
        name: nginx
        state: latest  # Ensures the latest version is installed

    - name: Copy the Nginx config file to /etc/nginx/sites-available
      copy:
        src: ./nginx.cfg
        dest: /etc/nginx/sites-available/nginx.cfg
        owner: root
        group: root
        mode: '0644'

    - name: Create symlink of the config file at /etc/nginx/sites-enabled
      file:
        src: /etc/nginx/sites-available/nginx.cfg
        dest: /etc/nginx/sites-enabled/nginx.cfg
        state: link

    - name: Restart Nginx to apply changes
      service:
        name: nginx
        state: restarted
        enabled: true
